routes:
  events:
    controller: EventWidgetController
#    capability: staff
    actions:
      - [index]
#      - [create, [POST], {capability: super_staff}]
      - [create, [POST]]
    routes:
      "(?P<id>[0-9]+)":
        actions:
          - [read]
          - [update, [PUT]]
          - [delete, [DELETE]]
